version: "3.1"
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment: 
      POSTGRES_PASSWORD: rocket
      POSTGRES_USER: postgres
      POSTGRES_DB: webappdb
    ports:
      - 5435:5435